# Introductions #

## Why this is important ##
The continuance of gender prejudice, which has been proved in numerous sectors, including 
STEM fields, where women have made progress but are still less likely to continue a career or 
be paid comparably to their male counterparts As we recover from the pandemic, it is more vital 
than ever for businesses to realize the benefits of gender equality.Gender pay disparities must 
be reported. It displays accountability and gives employers the tools they need to identify and 
overcome impediments to women's advancement in the workplace and they play a big part as 
well in the work enviorment. The questions we are trying to identify throughout this analysis is:
What is the gender split in high-earning positions? Are factors such as gender, race, and 
ethnicity important in determining pay disparities? Is credit given to women in the same way it is 

## What the dataset will compose of ##
The gender pay gap analysis dataset will provide insight about.....
